name: Chess.com Rating Chart

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chess Rating Chart
        uses: mmzeynalli/chess-rating-chart@v1
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CHESS_COM_USERNAME: HongKongPh00ie
          CHESS_COM_TIME_CLASS: rapid
